---
# Install Jenkins CI playbook

- name: Install Jenkins based on what OS is detected 
  hosts: localhost
  become: yes
  become_method: sudo


 - import_tasks: redhat.yml
   when: ansible_facts['os_family']|lower == 'redhat'
 - import_tasks: debian.yml
   when: ansible_facts['os_family']|lower == 'debian'
 - import_tasks: fedora.yml
   when: ansible_facts['os_family']|lower == 'fedora'