

- name: Installing git
  yum:
    name: git
    state: present
  become: true  
       
- name: Installing wget
  yum:
    name: wget
    state: present
  become: true

- name: Installing openjdk
  yum:
    name: java-1.8.0-openjdk
    state: present
  become: true  

- name: Installing java
  yum:
    name: java
    state: present    
  become: true  

- name: Install the latest version of Jenkins
  dnf:
    name: jenkins
    state: latest
  become: true  